title: Jasmin Palmer
description: My personal site
remote_theme: mmistakes/minimal-mistakes@4.27.1
plugins:
  - jekyll-remote-theme

# Simple navigation setup for GitHub Pages
header_pages:
  - index.md
  - about.md
  - projects.md